openapi: 3.0.0
info:
  title: Choir Hub API
  version: 1.0.0
  description: API documentation for Choir Hub

servers:
  - url: http://localhost:5000/api
    description: Local dev server

paths:
  /users:
    get:
      summary: Get all users
      responses:
        "200":
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: number
        email:
          type: string
        username:
          type: string
